### PR TITLE
chore: fix ubuntu_widgets git ref

### PR DESCRIPTION
**Pull request by d-loose**
This should fix the recent snap build failures

### CODE REVIEW

**Comment by rpjday** [comment]
While this is not a high priority, I use this snap for an example build in the Snapcraft 101 course and, recently, it's had some breakage. When the build error is resolved, can someone apply some Git tags to known good builds so I can guarantee students can build this snap?

**Comment by jpnurmi** [comment]
@d-loose pinning the dart_style version similarly how we did in subiquity client could help with the difference between dart format and build_runner. on the other hand, we could even try migrating to flutter 3.10 / dart 3.0 unless we have any unmigrated dependencies or anything else that blocks us from migrating?

- https://github.com/canonical/subiquity_client.dart/pull/53

**Comment by d-loose** [comment]
Thanks! Yes I think it's time to migrate - I'll give it a try and see if there are any blockers

**Comment by d-loose** [comment]
Ah, mockito is still causing conflicts:
```
Because mockito >=5.0.6 <5.4.0 depends on test_api >=0.2.1 <0.5.0 and every version of flutter_test from sdk depends on test_api 0.5.1, mockito >=5.0.6 <5.4.0 is incompatible with flutter_test from sdk.
So, because os_logo depends on both flutter_test from sdk and mockito 5.3.2, version solving failed.
```

IIRC we didn't want to upgrade to mockito 5.4.0 due to some issues with mocks not being properly regenerated (https://github.com/canonical/ubuntu-desktop-installer/pull/1801)

**Comment by jpnurmi** [comment]
The issue was probably deeper under the hood, perhaps in build_runner which controls the cache? Not sure if the issue is still there but at least it hasn't surfaced in the projects we've migrated so far. :)

**Comment by d-loose** [comment]
Superseded by #343

**Comment by d-loose** [comment]
> While this is not a high priority, I use this snap for an example build in the Snapcraft 101 course and, recently, it's had some breakage. When the build error is resolved, can someone apply some Git tags to known good builds so I can guarantee students can build this snap?

@rpjday [snap builds successfully](https://github.com/canonical/workshops/actions/runs/5046620123) again :)

**Pull request closed without merging**
