### PR TITLE
Check if context is mounted in showConfigEditorDialog()

### LINKED ISSUE #323: showConfigEditorDialog() uses build context across async gap
Upgrading to Flutter 3.7 revealed an issue in `showConfigEditorDialog()`:

> Don't use 'BuildContext's across async gaps.
> Try rewriting the code to not reference the 'BuildContext'. dart([use_build_context_synchronously](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html))

```dart
Future<void> showConfigEditorDialog(
  BuildContext context, {...}) async {
  final configSchema = await loadConfigSchema(assetName);
  // context is no longer guaranteed to be valid/mounted
  return showDialog(context: context, ...);
}
```

https://github.com/canonical/workshops/blob/main/lib/config_editor/config_editor_dialog.dart#L11-L29

### PR DESCRIPTION
**Pull request by d-loose**
Fix #323

P.S.
The linter doesn't seem to like
```dart
if(!context.mounted) return;
```

### CODE REVIEW

**Comment by jpnurmi** [comment]
I vaguely recall there was a reason to structure it like this to keep the code simple but what if we loaded the schema in the model or made the dialog stateful?

**Comment by jpnurmi** [comment]
Huh? The linter accepted it after all? :)

**Review by jpnurmi — APPROVED** [review]
much simpler than I thought  :) LGTM :+1:

**Comment by d-loose** [comment]
My comment might have been confusing: the linter is perfectly happy with
```dart
if(context.mounted) {
    ...
}
```
but not with
```dart
if(!context.mounted) return;
```

**Pull request merged**
